[2023-01-17T20:32:32.074+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:32:26.460136+00:00 [queued]>
[2023-01-17T20:32:32.190+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:32:26.460136+00:00 [queued]>
[2023-01-17T20:32:32.194+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:32:32.195+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T20:32:32.197+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:32:32.338+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_integrate_dataset> on 2023-01-17 20:32:26.460136+00:00
[2023-01-17T20:32:32.925+0000] {standard_task_runner.py:55} INFO - Started process 2537 to run task
[2023-01-17T20:32:32.958+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'extract_integrate_dataset', 'manual__2023-01-17T20:32:26.460136+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpx2elpfnw']
[2023-01-17T20:32:33.010+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask extract_integrate_dataset
[2023-01-17T20:32:33.321+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:32:26.460136+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T20:32:33.934+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_integrate_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T20:32:26.460136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T20:32:26.460136+00:00
[2023-01-17T20:32:33.940+0000] {logging_mixin.py:137} INFO - got file paths successfully
[2023-01-17T20:32:38.841+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T20:32:42.088+0000] {logging_mixin.py:137} INFO - loaded CSVs files to df successfully
[2023-01-17T20:34:43.866+0000] {logging_mixin.py:137} INFO - data integrated successfully
[2023-01-17T20:34:46.271+0000] {python.py:177} INFO - Done. Returned value was:         accident_year  ...  lsoa_of_driver
0                1983  ...            -1.9
1                1983  ...            -1.0
2                1983  ...            -1.0
3                1983  ...            -1.0
4                1983  ...            -1.0
...               ...  ...             ...
409618           1983  ...            -1.0
409619           1983  ...            -1.0
409620           1983  ...            -1.0
409621           1983  ...            -1.0
409622           1983  ...            -1.0

[409623 rows x 55 columns]
[2023-01-17T20:34:50.146+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-01-17T20:34:50.189+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-01-17T20:34:50.481+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_data_etl_pipeline, task_id=extract_integrate_dataset, execution_date=20230117T203226, start_date=20230117T203232, end_date=20230117T203450
[2023-01-17T20:34:51.378+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task extract_integrate_dataset (Object of type DataFrame is not JSON serializable; 2537)
[2023-01-17T20:34:51.559+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T20:34:52.359+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
