[2023-01-17T23:31:57.199+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:31:14.570382+00:00 [queued]>
[2023-01-17T23:31:57.259+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:31:14.570382+00:00 [queued]>
[2023-01-17T23:31:57.261+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:31:57.263+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T23:31:57.264+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:31:57.414+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_task> on 2023-01-17 23:31:14.570382+00:00
[2023-01-17T23:31:57.460+0000] {standard_task_runner.py:55} INFO - Started process 12212 to run task
[2023-01-17T23:31:57.496+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_task', 'manual__2023-01-17T23:31:14.570382+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpr7v01rh6']
[2023-01-17T23:31:57.503+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask cleanning_task
[2023-01-17T23:31:58.233+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:31:14.570382+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T23:31:58.480+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T23:31:14.570382+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T23:31:14.570382+00:00
[2023-01-17T23:32:06.028+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T23:32:29.628+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T23:32:29.662+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T23:32:29.706+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_task, execution_date=20230117T233114, start_date=20230117T233157, end_date=20230117T233229
[2023-01-17T23:32:29.781+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T23:32:29.840+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
