[2023-01-17T22:52:40.457+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:51:15.534550+00:00 [queued]>
[2023-01-17T22:52:40.666+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:51:15.534550+00:00 [queued]>
[2023-01-17T22:52:40.710+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:52:40.740+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T22:52:40.769+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:52:40.960+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_dataset> on 2023-01-17 22:51:15.534550+00:00
[2023-01-17T22:52:41.056+0000] {standard_task_runner.py:55} INFO - Started process 10041 to run task
[2023-01-17T22:52:41.120+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_dataset', 'manual__2023-01-17T22:51:15.534550+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp37od3qjw']
[2023-01-17T22:52:41.188+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask cleanning_dataset
[2023-01-17T22:52:42.092+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:51:15.534550+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T22:52:43.288+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T22:51:15.534550+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T22:51:15.534550+00:00
[2023-01-17T22:53:02.672+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T22:53:38.689+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T22:53:39.104+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T22:53:39.243+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_dataset, execution_date=20230117T225115, start_date=20230117T225240, end_date=20230117T225339
[2023-01-17T22:53:39.556+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T22:53:39.756+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
