[2023-01-17T22:56:27.385+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:55:37.346759+00:00 [queued]>
[2023-01-17T22:56:27.409+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:55:37.346759+00:00 [queued]>
[2023-01-17T22:56:27.410+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:56:27.411+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T22:56:27.412+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:56:27.451+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_dataset> on 2023-01-17 22:55:37.346759+00:00
[2023-01-17T22:56:27.471+0000] {standard_task_runner.py:55} INFO - Started process 10258 to run task
[2023-01-17T22:56:27.479+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_dataset', 'manual__2023-01-17T22:55:37.346759+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpy60brfna']
[2023-01-17T22:56:27.482+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask cleanning_dataset
[2023-01-17T22:56:27.621+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T22:55:37.346759+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T22:56:27.798+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T22:55:37.346759+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T22:55:37.346759+00:00
[2023-01-17T22:56:37.139+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T22:57:08.435+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T22:57:08.466+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T22:57:08.484+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_dataset, execution_date=20230117T225537, start_date=20230117T225627, end_date=20230117T225708
[2023-01-17T22:57:08.553+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T22:57:08.585+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
