[2023-01-17T20:43:36.230+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T20:42:50.452360+00:00 [queued]>
[2023-01-17T20:43:36.302+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T20:42:50.452360+00:00 [queued]>
[2023-01-17T20:43:36.303+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:43:36.304+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T20:43:36.305+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:43:36.412+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_dataset> on 2023-01-17 20:42:50.452360+00:00
[2023-01-17T20:43:36.442+0000] {standard_task_runner.py:55} INFO - Started process 3089 to run task
[2023-01-17T20:43:36.445+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_dataset', 'manual__2023-01-17T20:42:50.452360+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpf879acal']
[2023-01-17T20:43:36.461+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask cleanning_dataset
[2023-01-17T20:43:36.858+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T20:42:50.452360+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T20:43:39.894+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T20:42:50.452360+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T20:42:50.452360+00:00
[2023-01-17T20:43:44.770+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T20:44:07.171+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T20:44:07.206+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T20:44:07.313+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_dataset, execution_date=20230117T204250, start_date=20230117T204336, end_date=20230117T204407
[2023-01-17T20:44:07.414+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T20:44:07.466+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
