[2023-01-17T22:53:48.482+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:51:15.534550+00:00 [queued]>
[2023-01-17T22:53:48.631+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:51:15.534550+00:00 [queued]>
[2023-01-17T22:53:48.644+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:53:48.647+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T22:53:48.660+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:53:48.805+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_encoding_load_task> on 2023-01-17 22:51:15.534550+00:00
[2023-01-17T22:53:48.837+0000] {standard_task_runner.py:55} INFO - Started process 10100 to run task
[2023-01-17T22:53:48.855+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'transform_encoding_load_task', 'manual__2023-01-17T22:51:15.534550+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgghicqky']
[2023-01-17T22:53:48.860+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask transform_encoding_load_task
[2023-01-17T22:53:49.233+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:51:15.534550+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T22:53:49.593+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=transform_encoding_load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T22:51:15.534550+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T22:51:15.534550+00:00
[2023-01-17T22:53:58.741+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T22:53:59.118+0000] {logging_mixin.py:137} INFO - loaded after cleaning succesfully
[2023-01-17T22:54:03.263+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 146, in transform_encode_load
    df['first_road_class'] = encoder.fit_transform(np.array(df['first_road_class']).reshape(242842,-1))
ValueError: cannot reshape array of size 409623 into shape (242842,newaxis)
[2023-01-17T22:54:03.376+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_data_etl_pipeline, task_id=transform_encoding_load_task, execution_date=20230117T225115, start_date=20230117T225348, end_date=20230117T225403
[2023-01-17T22:54:03.477+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task transform_encoding_load_task (cannot reshape array of size 409623 into shape (242842,newaxis); 10100)
[2023-01-17T22:54:03.583+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T22:54:03.667+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
