[2023-01-17T23:06:39.435+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:05:32.924578+00:00 [queued]>
[2023-01-17T23:06:39.467+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:05:32.924578+00:00 [queued]>
[2023-01-17T23:06:39.468+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:06:39.468+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T23:06:39.469+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:06:39.502+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_task> on 2023-01-17 23:05:32.924578+00:00
[2023-01-17T23:06:39.527+0000] {standard_task_runner.py:55} INFO - Started process 10781 to run task
[2023-01-17T23:06:39.532+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_task', 'manual__2023-01-17T23:05:32.924578+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpsk6a0cp4']
[2023-01-17T23:06:39.537+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask cleanning_task
[2023-01-17T23:06:39.664+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_task manual__2023-01-17T23:05:32.924578+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T23:06:39.848+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T23:05:32.924578+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T23:05:32.924578+00:00
[2023-01-17T23:06:52.240+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T23:07:25.168+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T23:07:25.214+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T23:07:25.244+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_task, execution_date=20230117T230532, start_date=20230117T230639, end_date=20230117T230725
[2023-01-17T23:07:25.344+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T23:07:25.428+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
